### ISSUE TITLE
Site update reflects all the apps on bench

### ISSUE THREAD

**Issue by harshit-30** [frappe/press#602] opened 2022-11-23 08:36 UTC
My site only has these three apps installed:
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/46772424/203501871-b8239ff5-5121-41d8-8326-43588dbba8d7.png">

However, clicking on Update Now, reflects all the applications that are installed on the bench:
![Screenshot 2022-11-23 at 14 05 11](https://user-images.githubusercontent.com/46772424/203502174-ff4eca2d-264c-4a07-8413-df82a15110ba.png)

**Comment by balamurali27** [comment] 2022-11-24 11:32
Duplicate of #362

**Closed by balamurali27** 2022-11-24 11:32 UTC
