### ISSUE TITLE
feat: Permission for teams tab for users other than owner

### ISSUE THREAD

**Issue by hari-madhavan** [frappe/press#1127] opened 2023-10-27 13:43 UTC
Currently, there is a capability to provide access to individual custom benches and sites. However both adding/removing users and groups as well as setting permissions for the users and groups is now available only for the site owner. 

Can we have a permission setting based on which team management permission can be given to other members within the team ?

**Comment by BreadGenie** [comment] 2024-09-05 05:02
duplicate of #1984 
if not feel free to re-open

**Closed by BreadGenie** 2024-09-05 05:02 UTC
