### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by optibizpro** [frappe/press#855] opened 2023-06-06 17:56 UTC
IndexError: list index out of range

### App Versions
```
{
	"frappe": "14.36.1",
	"press": "0.7.0"
}

```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/press/press/api/account.py", line 307, in get
    team = get_current_team()
  File "apps/press/press/utils/__init__.py", line 60, in get_current_team
    team = team_dict[0].name
IndexError: list index out of range

```
### Request Data
```
{
	"type": "POST",
	"args": {},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/press.api.account.get"
}
```
### Response Data
```
{
	"exception": "IndexError: list index out of range"
}
```

![IndexError](https://github.com/frappe/press/assets/134145164/11b82ccf-0f5c-4a05-a3ad-21719a4197a6)

**Comment by shadrak98** [comment] 2023-06-07 05:28
@optibizpro Can you share some context on performing what actions you got this error?

**Comment by DevOpsFreako** [comment] 2023-06-07 09:27
@shadrak98 @optibizpro 

if you Got Answer then share With Me Also 

@shadrak98 
I'm Trying Frappe cloud  Local Development Environment Setup

But getting Error of     get_current_team() and obtain_certificate()

When Tryping to obtain tls-certificate manually As 

Server Error
IndexError: list index out of range

Now Checking With Inspect In Network 

{exception: "IndexError: list index out of range",…}
exc
: 
"[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 66, in application\\n    response = frappe.api.handle()\\n  File \\\"apps/frappe/frappe/api.py\\\", line 54, in handle\\n    return frappe.handler.handle()\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 45, in handle\\n    data = execute_cmd(cmd)\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 83, in execute_cmd\\n    return frappe.call(method, **frappe.form_dict)\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 1608, in call\\n    return fn(*args, **newargs)\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 304, in run_doc_method\\n    response = doc.run_method(method)\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 914, in run_method\\n    out = Document.hook(fn)(self, *args, **kwargs)\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 1264, in composer\\n    return composed(self, method, *args, **kwargs)\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 1246, in runner\\n    add_to_return_value(self, fn(self, *args, **kwargs))\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 911, in fn\\n    return method_object(*args, **kwargs)\\n  File \\\"apps/press/press/press/doctype/tls_certificate/tls_certificate.py\\\", line 36, in obtain_certificate\\n    get_current_team(),\\n  File \\\"apps/press/press/utils/__init__.py\\\", line 60, in get_current_team\\n    team = team_dict[0].name\\nIndexError: list index out of range\\n\"]"
exception
: 
"IndexError: list index out of range"


on Console Seeing This error 

request.js:457 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1608, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/handler.py", line 304, in run_doc_method
    response = doc.run_method(method)
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/press/press/press/doctype/tls_certificate/tls_certificate.py", line 36, in obtain_certificate
    get_current_team(),
  File "apps/press/press/utils/__init__.py", line 60, in get_current_team
    team = team_dict[0].name
IndexError: list index out of range

---------------------------------------------------------------------------------------------------------
Now When i try to check on my database 

press@p1:~/frappe$ mysql -u root -p
show databases;
use _bbddaf7dab4cb0ae
show tables;
select * from tabTeam;
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 2992
Server version: 10.6.12-MariaDB-0ubuntu0.22.04.1 Ubuntu 22.04

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| _bbddaf7dab4cb0ae  |
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
5 rows in set (0.000 sec)

MariaDB [(none)]> select * from tabTeam;
ERROR 1046 (3D000): No database selected
MariaDB [(none)]> use _bbddaf7dab4cb0ae
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [_bbddaf7dab4cb0ae]> select * from tabTeam;
Empty set (0.000 sec)


@shadrak98 can you help me out

**Comment by optibizpro** [comment] 2023-06-07 14:18
> @optibizpro Can you share some context on performing what actions you got this error?

@shadrak98 This is after I tried to access the site, from the site list by clicking on the ID field of the site

**Comment by rutwikhdev** [comment] 2023-06-12 14:43
Closing as duplicate of https://github.com/frappe/press/issues/854
Please follow the thread for updates on the issue

**Closed by rutwikhdev** 2023-06-12 14:43 UTC
