### ISSUE TITLE
New Site page takes time to load

### ISSUE THREAD

**Issue by pateljannat** [frappe/press#806] opened 2023-05-17 05:02 UTC
On FC when we try to create a new site, the page takes a while to load and in the mean time shows just a blank screen.

<img width="1440" alt="Screenshot 2023-05-17 at 10 29 20 AM" src="https://github.com/frappe/press/assets/31363128/705c7ab5-13fc-4761-99b6-c639babaeed4">

**Comment by NagariaHussain** [comment] 2023-05-20 14:12
Duplicate of #816

**Closed** 2023-05-20 14:12 UTC
