### ISSUE TITLE
New FR: Add from Gitlab

### ISSUE THREAD

**Issue by ashishsaretia** [frappe/press#571] opened 2022-11-09 10:36 UTC
Can we please have the ability to add the custom app via the GIT URL directly? 
The current system only allows the system to connect with GitHub and we use GITLAB-CE (Self-hosted) version throughout the company.

Ideally, instead of asking from Github - we can certainly ask for the REPO URL and authenticate respectively.

**Comment by adityahase** [comment] 2022-11-09 12:21
Duplicate of https://github.com/frappe/press/issues/458

**Closed by adityahase** 2022-11-09 12:21 UTC
